export const initialValuesForIndividual = {
    brief_description: '',
    property_name: '',
    address:'',
    latitude:'',
    longitude:'',
    city:'',
    state:'',
    zipcode:'',
    individual_or_development:'individual',
    category:'',
    type:'',
    property_type_id:'',
    property_subtype_id:'',
    brochure:[],
    energy_efficiency_rating:[],
    plan_image:[],
    miscellaneous:[],
    web_url:'',
    number_of_beds:0,
    number_of_baths:0,
    number_of_receptions:0,
    tenure:'',
    property_size:'',
    asking_price:'',
    rent_pay_type:'',
    minimum_acceptable_price:'',
    referral_fee_type:'',
    referral_fee:'',
    video_url:'',
    virtual_tour_link:'',
    key_features:'',
    tags:'',
    listing_type:3,
    public:0,
    videos:[],
    images:[],
    image:'',
    parking:'',
    include_sold_stc:'',
    garden:'',
    auction:''

}

export const initialValuesForDevelopment = {
    brief_description: '',
    property_name: '',
    address:'',
    latitude:'',
    longitude:'',
    city:'',
    state:'',
    zipcode:'',
    individual_or_development:'development',
    starting_price:'',
    end_price:'',
    category:'',
    type:'',
    property_type_id:'',
    phase_details:[],
    brochure:[],
    energy_efficiency_rating:[],
    plan_image:[],
    miscellaneous:[],
    web_url:'',
    referral_fee_type:'',
    referral_fee:'',
    video_url:'',
    virtual_tour_link:'',
    key_features:'',
    tags:'',
    public:0,
    videos:[],
    images:[],
    parking:'',
    include_sold_stc:'',
    garden:'',
    auction:'',
    total_phase:'',
    total_units:'',
    development_image:'',
    phaseFields: [{ phase_name: '', property_type_id: '', no_of_units: '', est_completion_date: '' }] ,
    fields:[{ apartment_name: '', asking_price: '', floor_number: '', property_size: '', number_of_beds: '', number_of_baths: '' }]
}

/**
 * 
 * {
		"apartment_name": "Apartment1",
		"phase_name": "phase1",
		"no_of_units": 4,
		"est_completion_date": "2023-03-14",
		"asking_price": 100000,
		"referral_fee_type": "Currency",
		"referral_fee": 10000,
		"number_of_beds": 1,
		"number_of_baths": 2,
		"number_of_receptions": 0,
		"floor_number": 2,
		"property_size": 1200,
		"tenure": "Lease Off",
		"property_type_id": 1
	}
 */